# Generated by Django 5.1.1 on 2025-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='content',
            new_name='content_english',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='location_english',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='title_english',
        ),
        migrations.AddField(
            model_name='event',
            name='content_greek',
            field=models.TextField(default='update in greek'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_greek',
            field=models.CharField(default='update in greek', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='title_greek',
            field=models.CharField(default='update in greek', max_length=200),
        ),
    ]
