# Generated by Django 5.1.1 on 2025-10-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='content',
            new_name='content_english',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='excerpt',
            new_name='excerpt_english',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='title',
            new_name='title_english',
        ),
        migrations.AddField(
            model_name='new',
            name='content_greek',
            field=models.TextField(default='update in greek'),
        ),
        migrations.AddField(
            model_name='new',
            name='excerpt_greek',
            field=models.TextField(blank=True, default='update in greek'),
        ),
        migrations.AddField(
            model_name='new',
            name='title_greek',
            field=models.CharField(default='update in greek', max_length=200),
        ),
    ]
