# Generated by Django 5.1.1 on 2025-10-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_content_new_content_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content_greek',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='excerpt_greek',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='title_greek',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
