# Generated by Django 5.1.1 on 2024-11-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='POSITIONS',
            new_name='position',
        ),
    ]
