# Generated by Django 5.1.1 on 2025-12-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='people',
            name='name_gr',
            field=models.CharField(default='Name In Greek', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='people',
            name='position',
            field=models.IntegerField(choices=[(0, 'President'), (1, 'Vice President'), (2, 'Secretary'), (3, 'Assistant Secretary'), (4, 'Treasurer'), (5, 'Assistant Treasurer'), (6, 'Member'), (7, 'Staff')], default=0),
        ),
    ]
