# Generated by Django 5.1.1 on 2025-01-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_rename_positions_people_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='position',
            field=models.IntegerField(choices=[(0, 'Πρόεδρος'), (1, 'Αντιπρόεδρος'), (2, 'Γραμματέας'), (3, 'Βοηθός Γραμματέας'), (4, 'Ταμίας'), (5, 'Βοηθός Ταμίας'), (6, 'Μέλος'), (7, 'Προσωπικό')], default=0),
        ),
    ]
