# Generated by Django 5.1.1 on 2026-05-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_rename_name_people_name_en_people_name_gr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='position',
            field=models.IntegerField(choices=[(0, 'President'), (1, 'Vice President'), (2, 'Secretary'), (3, 'Assistant Secretary'), (4, 'Treasurer'), (5, 'Assistant Treasurer'), (6, 'Member'), (7, 'Executive Director'), (8, 'Liaison Officer')], default=0),
        ),
    ]
