# Generated by Django 5.1.1 on 2024-12-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shippingdetail_basket_items_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
