# Generated by Django 5.1.1 on 2025-02-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shippingdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetail',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
