# Generated by Django 5.1.1 on 2024-12-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('one-off', 'One-Off Payment'), ('monthly', 'Monthly Subscription')], max_length=20),
        ),
    ]
