# Generated by Django 5.1.1 on 2024-12-03 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_donation_donation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='address2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='postcode',
            field=models.CharField(default=1111, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='state',
            field=models.CharField(default=1111, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
