# Generated by Django 5.1.1 on 2025-02-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_address_shippingdetail_address_for_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
