# Generated by Django 5.1.1 on 2025-05-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_donation_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='donation',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
