# Generated by Django 5.1.1 on 2025-08-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_donation_updated_at_donation_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('One-Off Payment', 'One-Off Payment'), ('Monthly Subscription', 'Monthly Subscription'), ('Thalassios Marathonios', 'Thalassios Marathonios')], max_length=50),
        ),
    ]
