# Generated by Django 5.1.1 on 2026-05-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_donation_donation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('One-Off Payment', 'One-Off Payment'), ('Monthly Subscription', 'Monthly Subscription'), ('Sea Marathon', 'Sea Marathon')], max_length=50),
        ),
    ]
