# Generated by Django 5.1.1 on 2024-11-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_as', models.CharField(choices=[('sufferer', 'Sufferer'), ('parent', 'Parent'), ('friend', 'Friend')], default='sufferer', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('home_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('work_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('heart_disease_description', models.CharField(max_length=100)),
                ('date_of_diagnosis', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
