# Generated by Django 5.1.1 on 2025-02-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
