# Generated by Django 5.1.1 on 2025-02-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_member_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='recurring_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
