# Generated by Django 5.1.1 on 2025-02-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_member_recurring_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
