# Generated by Django 5.1.1 on 2025-03-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_member_last_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='recurring_token',
        ),
    ]
