# Generated by Django 5.1.1 on 2025-03-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_remove_member_recurring_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
